import { registerNativeComponent } from './helpers.js'

export const Align = registerNativeComponent(AlignElement)
export const Background = registerNativeComponent(BackgroundElement)
export const Center = registerNativeComponent(CenterElement)
export const IntrinsicHeight = registerNativeComponent(IntrinsicHeightElement)
export const IntrinsicWidth = registerNativeComponent(IntrinsicWidthElement)
export const Flex = registerNativeComponent(FlexElement)
export const FlexChild = registerNativeComponent(FlexChildElement)
export const Padding = registerNativeComponent(PaddingElement)
export const Responder = registerNativeComponent(ResponderElement)
export const Scroll = registerNativeComponent(ScrollElement)
export const Sized = registerNativeComponent(SizedElement)
export const Stack = registerNativeComponent(StackElement)
export const Text = registerNativeComponent(TextElement)
export const Translate = registerNativeComponent(TranslateElement)
