import { registerNativeComponent } from './helpers.js'

export const Align = registerNativeComponent(AlignElement)
export const Background = registerNativeComponent(BackgroundElement)
export const Border = registerNativeComponent(BorderElement)
export const Center = registerNativeComponent(CenterElement)
export const Clip = registerNativeComponent(ClipElement)
export const CustomLayout = registerNativeComponent(CustomLayoutElement)
export const IntrinsicHeight = registerNativeComponent(IntrinsicHeightElement)
export const IntrinsicWidth = registerNativeComponent(IntrinsicWidthElement)
export const Flex = registerNativeComponent(FlexElement)
export const FlexChild = registerNativeComponent(FlexChildElement)
// export const Layer = registerNativeComponent(LayerElement)
export const Padding = registerNativeComponent(PaddingElement)
// export const Responder = registerNativeComponent(ResponderElement)
// export const Scroll = registerNativeComponent(ScrollElement)
export const Size = registerNativeComponent(SizeElement)
export const Stack = registerNativeComponent(StackElement)
// export const Text = registerNativeComponent(TextElement)
// export const Translate = registerNativeComponent(TranslateElement)
