import { registerNativeComponent } from './helpers.js'

export const Aligned = registerNativeComponent(AlignedElement)
export const Background = registerNativeComponent(BackgroundElement)
export const Border = registerNativeComponent(BorderElement)
export const Center = registerNativeComponent(CenterElement)
export const Clip = registerNativeComponent(ClipElement)
export const CustomLayout = registerNativeComponent(CustomLayoutElement)
export const IntrinsicHeight = registerNativeComponent(IntrinsicHeightElement)
export const IntrinsicWidth = registerNativeComponent(IntrinsicWidthElement)
export const Flex = registerNativeComponent(FlexElement)
export const FlexChild = registerNativeComponent(FlexChildElement)
export const Layer = registerNativeComponent(LayerElement)
export const Padded = registerNativeComponent(PaddedElement)
export const Responder = registerNativeComponent(ResponderElement)
export const Sized = registerNativeComponent(SizedElement)
export const Stack = registerNativeComponent(StackElement)
export const Text = registerNativeComponent(TextElement)
export const Translated = registerNativeComponent(TranslatedElement)
export const Paragraph = registerNativeComponent(ParagraphElement)
export const TextSpanC = registerNativeComponent(TextSpan)
export const DecorationSpanC = registerNativeComponent(DecorationSpan)
export const ResponderSpanC = registerNativeComponent(ResponderSpan)
